site_name: utau-zh-docs
site_description: UTAU相关各种文档的简体中文翻译堆积处。
site_author: 隋卞

nav:
        - 首页:
                - 'README.md'
                - 'CONTRIBUTORS.md'
                - 'CONTRIBUTING.md'
        - 文档:
                - 'docs/SHIRO-readme/SHIRO-readme.md/'
                - 'docs/presamp-ini-spec/presamp-ini-spec.md/'
                - 'docs/UTAU-plugin-dev/UTAU-plugin-dev.md/'
                - 'docs/setParam-plugin-dev/setParam-plugin-dev.md/'
                - 'docs/rentan-info/rentan-info.md/'
                - 'docs/doppeltler_readme_zh/doppeltler_readme_zh.md/'
                - 'docs/UTAU-english-phoneme-list/UTAU-english-phoneme-list.md/'
                - 'docs/原音设定1_oto条目到底包含了什么/原音设定1.md'
                - 'docs/UTAU-batchfile-analyze/UTAU-batchfile-analyze.md'
                - 'docs/fuck-utau/fuck-utau.md'
                - 'docs/utau_pitch_string/utau-pitch-analysis.md'

theme:
        name: 'material'
        language: 'zh'
        custom_dir: overrides
        favicon: images/favicon.ico
        features:
                - tabs
                - navigation.instant
                - navigation.tabs
        icon:
                repo: fontawesome/brands/github-alt

        logo: images/favicon.ico
        font: false

copyright: 隋卞 et al.，在<a href="https://creativecommons.org/licenses/by-sa/4.0/legalcode.zh-Hans" target="_blank">知识共享许可协议—署名—相同方式共享 4.0 协议国际版</a>下发布

plugins:
        - git-revision-date:
                enabled_if_env: CI
        - git-revision-date-localized:
                type: timeago
                time_zone: Asia/Shanghai
                locale: zh # cannot follow the default lang
                fallback_to_build_date: true
        - search:
                lang: # no zh, workaround
                        - ja
                        - en

repo_url: https://github.com/SuibianP/utau-zh-docs
repo_name: SuibianP/utau-zh-docs

markdown_extensions:
        - toc:
                permalink: ♬
                slugify: !!python/name:chinese_slugify.chinese_slugify
        - pymdownx.highlight:
                linenums: true
                guess_lang: true
        - pymdownx.inlinehilite
        - pymdownx.superfences
        - pymdownx.snippets:
                check_paths: true
        - pymdownx.tilde
        - pymdownx.caret
        - pymdownx.mark
        - pymdownx.betterem:
                smart_enable: all
        - footnotes

extra:
        social:
                - icon: fontawesome/brands/github
                  link: https://github.com/SuibianP
                - icon: fontawesome/brands/qq
                  link: https://qm.qq.com/cgi-bin/qm/qr?k=mJazCWZGab4flBhFeyEGVCwi6fD0eZMh&noverify=0
